// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcblgzefcszzpflbwuiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjYmxnemVmY3N6enBmbGJ3dWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NDg0ODMsImV4cCI6MjA5MDEyNDQ4M30.lSle8dblZJ2cvn7FsSx49gbPcKD1uGEUbw8mSFjlnrc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});